export const shopActionType = {
    // UPADATE_COLLECTION: 'UPDATE_COLLECTION'
    FATCH_DATA_START: 'FATCH_DATA_START',
    FATCH_DATA_SUCCESS: 'FATCH_DATA_SUCCESS',
    FATCH_DATA_FAIL: 'FATCH_DATA_FAIL'
}